as gallery in destinE

diff --git a/.github/workflows/build_myst_page.yml b/.github/workflows/build_myst_page.yml
--- a/.github/workflows/build_myst_page.yml
+++ b/.github/workflows/build_myst_page.yml
@@ -57,6 +57,23 @@ jobs:
       - name: Generate Buttons in index file
         run: python scripts/indexbutton.py
 
+      - name: Copy images into final HTML folder
+        run: |
+          echo "Copy dynamic images into HTML folder..."
+          mkdir -p "${{ github.workspace }}/_build/html/img"
+          cp -r "${{ github.workspace }}/img/"* "${{ github.workspace }}/_build/html/img/" || true
+      
+        
+      - name: DEBUG — check img/ in workspace
+        run: |
+          echo "=== WORKSPACE LOCATION ==="
+          pwd
+          echo "=== LIST OF FILES ==="
+          ls -R .
+          echo "=== LIST OF ./img ==="
+          ls -R img || echo "img not found"
+
+
       - name: Generate myst.yml and TOC
         run: python scripts/build_myst_yml.py
 
@@ -68,12 +85,6 @@ jobs:
           echo "=== IMAGES IN _build/html/img ==="
           ls -R _build/html/img || echo "No html img folder"
 
-    
-      - name: Copy images into final HTML folder
-        run: |
-          echo "Copying img/ into _build/html/img/ ..."
-          mkdir -p _build/html/img
-          cp -r img/* _build/html/img/ || true
 
       - name: DEBUG — show final deploy folder images
         run: |
